/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;

public class App {
    public static void main(String[] args) {

        String inputFile = "C:\\Users\\Saify\\OneDrive\\Desktop\\bmp.bmp";
        String outputFile = "C:\\Users\\Saify\\OneDrive\\Desktop\\bmpEdited.bmp";
        //String inputFile=args[0];
        //String outputFile=args[1];
        //String transformName= args[2];
        Bitmap bitmap = new Bitmap(inputFile);
        bitmap.convertToBlackAndWhite();
        bitmap.writeToFile(outputFile);


    }
}
